require("copilot").setup({
	suggestion = { enabled = false },
	panel = { enabled = false },
	copilot_model = "claude-4",
	filetypes = {
		dockerfile = true,
		go = true,
		gothtmltmpl = true,
		gotexttmpl = true,
		hcl = true,
		helm = true,
		javascript = true,
		json = true,
		lua = true,
		make = true,
		markdown = true,
		python = true,
		sh = true,
		typescript = true,
		yaml = true,
		["*"] = false,
	},
})
