#!/usr/bin/env bash

OUTPUT=""

openvpn=$(pgrep -c openvpn$)
[ "$openvpn" -gt 0 ] && OUTPUT=$(eval printf "%.0s" "{1..$openvpn}")

globalprotect=$(pgrep -c gpclient$)
[ "$globalprotect" -gt 0 ] && OUTPUT=${OUTPUT}$(eval printf '%.0s' "{1..$globalprotect}")

echo "$OUTPUT" | sed -e 's/\(.\)/\1 /g'
